######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 9 08:48:58 2011
######################################################################

CONFIG += qdbus
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
