/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a thermometerwatcher.h:thermometerwatcher.cpp -i types.h xml/thermometerwatcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "thermometerwatcher.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ThermometerWatcherAdaptor
 */

ThermometerWatcherAdaptor::ThermometerWatcherAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ThermometerWatcherAdaptor::~ThermometerWatcherAdaptor()
{
    // destructor
}

void ThermometerWatcherAdaptor::MeasurementReceived(const QVariantMap &measure)
{
    // handle method call org.bluez.ThermometerWatcher.MeasurementReceived
    QMetaObject::invokeMethod(parent(), "MeasurementReceived", Q_ARG(QVariantMap, measure));
}

